name: Build and publish JAR

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
            #- name: Build with Gradle
            #  run: ./gradlew conductor-server:shadowJar --stacktrace
      - name: Build with Gradle
        run: mkdir -p ./server/build/libs/
      - name: Build with Gradle
        run: echo "test" > ./server/build/libs/conductor-server-test-all.jar
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "server/build/libs/conductor-server-*-all.jar"
          commit: "${{ github.sha }}"
          tag: "build-${{ github.sha }}"
          token: ${{ github.token }}

